### ISSUE TITLE
Compiling with TDM-GCC on Windows fails - undefined reference to `qsort_r'

### ISSUE THREAD

**Issue by shashfrankenstien** [noporpoise/sort_r#14]
OS: Windows 10
Compiler: TDM-GCC-64

Compilation fails with the below error - 
```
sort_r.h:288: undefined reference to `qsort_r'
```
I was able to fix it by removing the check for `__MINGW32__ ` in the `_SORT_R_LINUX` definition

**Comment by noporpoise** [comment]
I finally got around to merging a PR that fixes this issue. Thanks for raising.
